Update criarteste

diff --git a/Modules/criarteste b/Modules/criarteste
--- a/Modules/criarteste
+++ b/Modules/criarteste
@@ -1,7 +1,8 @@
 #!/bin/bash
-IP=$(cat /etc/IP)
+
+sudo IP=$(cat /etc/IP)
 if [ ! -d /etc/SSHPlus/userteste ]; then
-mkdir /etc/SSHPlus/userteste
+  sudo mkdir /etc/SSHPlus/userteste
 fi
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Create test user" ; tput sgr0
 echo ""
@@ -9,56 +10,56 @@ echo ""
 echo ""
 for testeson in $(ls /etc/SSHPlus/userteste |sort |sed 's/.sh//g')
 do
-echo "$testeson"
+  echo "$testeson"
 done
 echo ""
 echo -ne "\033[1;32mUser name\033[1;37m: "; read nome
 if [[ -z $nome ]]
 then
-echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid name." ; echo "" ; tput sgr0
-	exit 1
+  echo ""
+  tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid name." ; echo "" ; tput sgr0
+  exit 1
 fi
-awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
+sudo awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
 if grep -Fxq "$nome" /tmp/users
 then
-	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
-	exit 1
+  tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
+  exit 1
 fi
 echo -ne "\033[1;32mPassword\033[1;37m: "; read pass
 if [[ -z $pass ]]
 then
-echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Password empty or invalid." ; echo "" ; tput sgr0
-	exit 1
+  echo ""
+  tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Password empty or invalid." ; echo "" ; tput sgr0
+  exit 1
 fi
 echo -ne "\033[1;32mLimit\033[1;37m: "; read limit
 if [[ -z $limit ]]
 then
-echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
-	exit 1
+  echo ""
+  tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
+  exit 1
 fi
 echo -ne "\033[1;32mMinutes \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
 if [[ -z $limit ]]
 then
-echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
-	exit 1
+  echo ""
+  tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
+  exit 1
 fi
-useradd -M -s /bin/false $nome
-(echo $pass;echo $pass) |passwd $nome > /dev/null 2>&1
-echo "$pass" > /etc/SSHPlus/senha/$nome
-echo "$nome $limit" >> /root/users.db
+sudo useradd -M -s /bin/false $nome
+(echo $pass;echo $pass) | sudo passwd $nome > /dev/null 2>&1
+echo "$pass" | sudo tee /etc/SSHPlus/senha/$nome > /dev/null
+echo "$nome $limit" | sudo tee -a /root/users.db > /dev/null
 echo "#!/bin/bash
-pkill -f "$nome"
-userdel --force $nome
-grep -v ^$nome[[:space:]] /root/users.db > /tmp/ph ; cat /tmp/ph > /root/users.db
-rm /etc/SSHPlus/senha/$nome > /dev/null 2>&1
-rm -rf /etc/SSHPlus/userteste/$nome.sh
-exit" > /etc/SSHPlus/userteste/$nome.sh
-chmod +x /etc/SSHPlus/userteste/$nome.sh
-at -f /etc/SSHPlus/userteste/$nome.sh now + $u_temp min > /dev/null 2>&1
+sudo pkill -f "$nome"
+sudo userdel --force $nome
+sudo grep -v ^$nome[[:space:]] /root/users.db > /tmp/ph ; sudo cat /tmp/ph > /root/users.db
+sudo rm /etc/SSHPlus/senha/$nome > /dev/null 2>&1
+sudo rm -rf /etc/SSHPlus/userteste/$nome.sh
+exit" | sudo tee /etc/SSHPlus/userteste/$nome.sh > /dev/null
+sudo chmod +x /etc/SSHPlus/userteste/$nome.sh
+sudo at -f /etc/SSHPlus/userteste/$nome.sh now + $u_temp min > /dev/null 2>&1
 clear
 echo -e "\E[44;1;37m     Test User Created     \E[0m"
 echo ""
